# Generated by Django 2.2 on 2019-08-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=20)),
                ('activity_time', models.CharField(max_length=200)),
                ('activity_location', models.CharField(max_length=30)),
                ('activity_abstract', models.TextField()),
                ('activity_peopleneed', models.IntegerField(default=0)),
                ('activity_tips', models.TextField()),
                ('activity_status', models.CharField(choices=[('N', 'NotStart'), ('O', 'Ongoing'), ('F', 'Finished')], max_length=1)),
                ('activity_items', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Activitytakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attender_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_name', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('admin_password', models.CharField(default='', max_length=20)),
                ('power_create_camp', models.BooleanField(default=False)),
                ('power_create_course', models.BooleanField(default=False)),
                ('power_create_activity', models.BooleanField(default=False)),
                ('power_create_administrator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=40)),
                ('introduce', models.TextField()),
                ('people_oriented', models.TextField()),
                ('signin_tips', models.TextField()),
                ('signin_deadline', models.CharField(max_length=100)),
                ('permission', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campattend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('camp_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Campclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('student_number', models.IntegerField(default=0)),
                ('camp_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Campsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('camp_id', models.IntegerField()),
                ('campclass_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('teacher', models.CharField(max_length=40)),
                ('abstract', models.TextField()),
                ('belongto_camp', models.CharField(max_length=40)),
                ('belongto_campclass', models.CharField(max_length=40)),
                ('number_bystander', models.IntegerField(default=0)),
                ('bystand_tips', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coursebystander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coursefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('ppt_name', models.CharField(blank=True, default='', max_length=100)),
                ('ppt', models.FileField(blank=True, upload_to='ppt')),
                ('video_name', models.CharField(blank=True, default='', max_length=100)),
                ('video', models.FileField(blank=True, upload_to='video')),
                ('text_name', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.FileField(blank=True, upload_to='text')),
                ('others_name', models.CharField(blank=True, default='', max_length=100)),
                ('others', models.FileField(blank=True, upload_to='othersFile')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_gender', models.CharField(choices=[('m', '男'), ('f', '女')], max_length=1)),
                ('user_weixinnumber', models.CharField(max_length=20)),
                ('user_telephone', models.CharField(max_length=11)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usercompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('brand_name', models.CharField(default='无', max_length=40)),
                ('website', models.CharField(default='无', max_length=50)),
                ('app_or_publicAccounts', models.CharField(default='无', max_length=20)),
                ('startup_time', models.CharField(max_length=30)),
                ('center_city', models.CharField(max_length=10)),
                ('membership', models.IntegerField(default=0)),
                ('abstract', models.TextField()),
                ('main_operational_data', models.TextField()),
                ('income_scale', models.CharField(max_length=20)),
                ('financing_situation', models.CharField(choices=[('N', '尚未获得融资'), ('seed/angel', '已完成种子/天使融资'), ('pre-A', '已完成pre-A轮融资'), ('A', '已完成A轮融资'), ('refuse', '不方便透露'), ('others', '其他')], max_length=15)),
                ('value_of_assessment', models.CharField(default='', max_length=20)),
                ('additions', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_birthday', models.CharField(max_length=30)),
                ('user_company', models.IntegerField()),
                ('user_post', models.CharField(choices=[('F', '创始人'), ('CF', '联合创始人'), ('P', '董事长'), ('CEO', 'CEO'), ('Others', '其他')], max_length=30)),
                ('user_city', models.CharField(max_length=10)),
                ('user_referee1_message', models.TextField()),
                ('user_referee2_message', models.TextField()),
                ('user_referee3_message', models.TextField()),
                ('user_other_tips_message_question_for_absenceitem', models.CharField(max_length=4)),
                ('reasons_for_signin', models.TextField()),
                ('contribution_to_others', models.TextField()),
                ('messageway_to_camp', models.CharField(choices=[('weixin', '微信朋友圈'), ('friend', '朋友推荐'), ('Pubaccount', '未来之星公众号：EdStars未来同学会'), ('web', '好未来官网'), ('media', '媒体报道'), ('others', '其他')], max_length=20)),
                ('educated_condition', models.CharField(choices=[('PhD', '博士研究生'), ('MBA', '硕士研究生'), ('Bachelor', '本科'), ('College', '专科'), ('Others', '其他')], max_length=10)),
                ('user_educondition_time_detials', models.TextField()),
                ('user_beforestartup_company_condition', models.TextField()),
            ],
        ),
    ]
